-- pg_cron schedules on the production project, recorded here because pg_cron
-- state lives only in the database and is otherwise invisible to the repo.
-- Reflects the state as of 2026-09-11. Verify with:
--     select jobid, jobname, schedule, active from cron.job order by jobid;
--
-- refresh-odds is the ONLY writer of line_history, which is the source of every
-- "current close" and every CLV figure. It ran ONCE A DAY until 2026-09-11,
-- while the code comments claimed every 15 minutes. At that cadence the
-- project's central timing finding (+1.55 CLV inside the first six hours) was
-- unmeasurable, and the CLV tab showed a "current" line a day behind the books
-- beside it. Each call costs 2 Odds API credits; hourly is ~1,400 a month
-- against a balance in the tens of thousands.
--
--   job  name                        schedule        note
--   2    refresh-public-betting      REMOVED 2026-10-07  -- see note below
--   3    refresh-weather-wednesday   0 9 * * 3       weekly
--   4    refresh-injuries            40 12 * * *     daily  -- FIXED 2026-10-08
--   9    refresh-odds-daily          0 * * * *       HOURLY since 2026-09-11 (was 0 12 * * *)
--   13   log-clv-daily               30 12 * * *     daily; redundant with the 3-hourly
--                                                    GitHub log-clv workflow, harmless
--
-- The change that was applied:
select cron.alter_job(9, schedule => '0 * * * *');


-- refresh-public-betting (job 2), removed 2026-10-07
-- ---------------------------------------------------
-- Ran 904 times, every one reported "succeeded", and wrote zero rows. It
-- called api.actionnetwork.com/web/v1/games, which Action Network has retired:
-- the endpoint answers 404 and the function returns 500. pg_cron called it a
-- success because net.http_post completed -- the job's status says the request
-- was made, never that the response was useful, which is worth remembering
-- before trusting any "succeeded" in cron.job_run_details.
--
--   select cron.unschedule(2);
--
-- The public_betting table it fed is KEPT, empty, because two things read it:
-- score_week.fetch_public_betting() -> detect_rlm() -> assign_confidence_tier(),
-- and the frontend's GameDetailPanel. With the table empty, detect_rlm has
-- always returned {"flag": False}, so every tier rule that requires an RLM
-- flag has been unreachable since the app was built. That is a dormant
-- feature, not a broken one, and switching it on is an NFL behaviour change:
-- fed from nfl_public_splits it would flag 15 of 80 games this season, with
-- the model already on the sharp side in 7 of the 14 graded ones (8-6). Not
-- done, deliberately, and not to be done without asking.


-- refresh-injuries (job 4), fixed 2026-10-08
-- -----------------------------------------
-- 486 runs, every one "succeeded", zero rows written, for the life of the app.
-- ESPN nests injuries by team (payload.injuries is 32 team objects each with
-- their own .injuries array); the function read it as a flat list. Every
-- athlete lookup was undefined and the guard dropped all 32 teams, so it
-- returned {success: true, count: 0} and pg_cron agreed.
--
-- This one had teeth. The spread, residual and movement models all carry ten
-- inj_* features and were TRAINED on real values, while injury_flags was empty
-- and fetch_injury_aggregates zero-filled them at serve time -- the exact
-- train/serve skew its own docstring warns about. inj_qb_out_home and
-- inj_qb_out_away have been 0 for every game ever scored. A starting
-- quarterback ruled out moved our number not at all while moving the market
-- seven points.
--
-- After the fix: 282 rows across 32 teams (194 questionable, 76 out, 12
-- doubtful), 3 quarterbacks out. An empty parse is now an explicit 500 rather
-- than a cheerful success, and it refuses to wipe a populated table.
--
-- Two notes for whoever reads this next:
--   * The feature follows ESPN's official designation. A player widely
--     expected to be out can sit at "Questionable" until game day, so
--     inj_qb_out can be 0 on a quarterback nobody expects to play.
--   * injury_flags.is_qb_override / qb_downgrade_pts are vestigial:
--     fetch_injury_aggregates never reads them and score_week hardcodes
--     "qb_override": False on every projection. The manual override the UI
--     implies does not exist. Left alone, not wired in.


-- line_predictions versioning + clv_tracking preference, 2026-10-08
-- -----------------------------------------------------------------
-- team_metrics held no 2026 rows until 2026-10-08, so 2026 predictions were
-- built from end-of-2025 form. Checked per freeze timestamp the damage was
-- narrower than it looked: weeks 1-3 were frozen before any 2026 week had
-- finished, so pure-2025 prior WAS the correct point-in-time answer and v2
-- reproduces v1 exactly there. Weeks 4, 5 and 6 are the affected ones.
--
-- Rather than overwrite, line_predictions is now versioned: the unique index
-- moved from (game_id, bet_type) to (game_id, bet_type, model_version).
-- movement_v1 rows are what the app actually served and are never deleted;
-- movement_v2 rows are the same models fed point-in-time metrics. 186 of each.
-- clv_tracking does DISTINCT ON (game_id, bet_type) preferring v2, so the
-- board shows 186 rows and not 372 -- verified, and the fan-out it prevents is
-- the same one that once turned 73 CFB predictions into 75.
--
-- Two leaks found while building the reconstruction, both caught by the rule
-- that weeks 1-3 MUST reproduce v1 exactly:
--   * the observed-weather table is one row per game refreshed weekly, so it
--     holds a forecast made AFTER each freeze. Including it flipped eight
--     totals in weeks 1-3 while leaving the spreads identical. Weather is now
--     passed empty, as v1 effectively had it.
--   * injury_flags has no history at all, so inj_* stays zero in v2 weeks 1-6.
--     Weeks 7+ carry real injuries, which is a real seam in the v2 series.
--
-- v2 is not a track record: nobody could have bet it, because the app showed
-- v1 at the time. It is the best estimate of what the model would have said.
-- The trap deliberately avoided: v2's weeks 4-6 must NOT be used to choose
-- qualifying thresholds that are then graded on those same games.
